# Generated by Django 5.2.6 on 2025-09-05 20:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', ckeditor.fields.RichTextField()),
                ('description', ckeditor.fields.RichTextField()),
                ('is_featured', models.BooleanField(default=False)),
                ('technologies', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, choices=[('fullstack', 'fullstack'), ('backend', 'backend'), ('frontend', 'frontend'), ('mobile', 'mobile'), ('scraping', 'scraping'), ('bots', 'bots'), ('data-analysis', 'data-analysis'), ('cybersecurity', 'cybersecurity')], max_length=50, null=True)),
                ('image', models.ImageField(upload_to='projects/')),
                ('url_github', models.CharField(blank=True, max_length=255, null=True)),
                ('url_blog_project', models.CharField(blank=True, max_length=255, null=True)),
                ('url_demo_live', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
